#import "BrowserViewController.h"
#import "../UI/SettingsViewController.h"
#import "../UI/NativeDrawerViewController.h"
#import "../Diagnostics/DiagnosticsStore.h"
#import "../Scripts/DisplayScripts.h"
#import "../Scripts/DiagnosticsScripts.h"
#import "../Scripts/RuntimeScripts.h"
#import "BrowserViewController+Navigation.h"
#import <WebKit/WebKit.h>

static NSString * const SXNativeUIKey = @"ScarletXNativeUI";

@interface BrowserViewController () <WKNavigationDelegate, WKUIDelegate, WKScriptMessageHandler, NativeDrawerViewControllerDelegate>
@property(nonatomic,strong) WKWebView *webView; @property(nonatomic,strong) NSURL *pendingURL; @property(nonatomic,assign) CFTimeInterval navigationStartTime; @property(nonatomic,assign) CFTimeInterval requestStartTime; @property(nonatomic,assign) NSInteger navigationSession; @property(nonatomic,assign) BOOL requestPending; @property(nonatomic,copy) NSString *navigationReason; @property(nonatomic,strong) NativeDrawerViewController *nativeDrawer;
@end
@implementation BrowserViewController
- (void)viewDidLoad { [super viewDidLoad]; self.view.backgroundColor=UIColor.systemBackgroundColor; [[DiagnosticsStore shared] addEvent:@"App launched" detail:@"Browser view created" url:nil]; WKWebViewConfiguration *config=[WKWebViewConfiguration new]; WKUserContentController *cc=[WKUserContentController new]; [cc addScriptMessageHandler:self name:@"scarletx"]; [DisplayScripts installSettingsScriptInto:cc]; [DisplayScripts installDisplayCustomizationInto:cc]; [DiagnosticsScripts installFlagsInto:cc]; [RuntimeScripts installInto:cc]; BOOL nativeUI=[[NSUserDefaults standardUserDefaults] boolForKey:SXNativeUIKey]; if(nativeUI){ NSString *bridge=@"(function(){if(window.__scarletXNativeDrawerInstalled)return;window.__scarletXNativeDrawerInstalled=true;document.addEventListener('click',function(e){var p=e.target&&e.target.closest?e.target.closest('[data-testid=\\\"DashButton_ProfileIcon_Link\\\"]'):null;if(!p)return;e.preventDefault();e.stopPropagation();if(e.stopImmediatePropagation)e.stopImmediatePropagation();try{window.webkit.messageHandlers.scarletx.postMessage({type:'native-drawer'});}catch(_){}},true);})();"; [cc addUserScript:[[WKUserScript alloc] initWithSource:bridge injectionTime:WKUserScriptInjectionTimeAtDocumentEnd forMainFrameOnly:YES]]; } config.userContentController=cc; config.websiteDataStore=WKWebsiteDataStore.defaultDataStore; config.allowsInlineMediaPlayback=YES; config.mediaTypesRequiringUserActionForPlayback=WKAudiovisualMediaTypeNone; self.webView=[[WKWebView alloc] initWithFrame:CGRectZero configuration:config]; self.webView.customUserAgent=@"Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/140.0.7339.122 Mobile/15E148 Safari/604.1"; self.webView.navigationDelegate=self; self.webView.UIDelegate=self; self.webView.allowsBackForwardNavigationGestures=YES; self.webView.translatesAutoresizingMaskIntoConstraints=NO; [self.view addSubview:self.webView]; [NSLayoutConstraint activateConstraints:@[[self.webView.topAnchor constraintEqualToAnchor:self.view.safeAreaLayoutGuide.topAnchor],[self.webView.leadingAnchor constraintEqualToAnchor:self.view.leadingAnchor],[self.webView.trailingAnchor constraintEqualToAnchor:self.view.trailingAnchor],[self.webView.bottomAnchor constraintEqualToAnchor:self.view.bottomAnchor]]]; if(self.pendingURL){NSURL*u=self.pendingURL;self.pendingURL=nil;[self loadURL:u reason:@"pending"];}else[self goHome]; }
- (void)openExternalURL:(NSURL*)url source:(NSString*)source { if(!url)return; NSURL*target=[self unwrapScarletURL:url]; dispatch_async(dispatch_get_main_queue(),^{if(!self.isViewLoaded)self.pendingURL=target;else[self loadURL:target reason:source];}); }
- (void)userContentController:(WKUserContentController*)u didReceiveScriptMessage:(WKScriptMessage*)m { if(![m.name isEqual:@"scarletx"])return; if([m.body isEqual:@"settings"]){[self openSettings];return;} if([m.body isKindOfClass:NSDictionary.class]&&[m.body[@"type"] isEqual:@"native-drawer"]){ if([[NSUserDefaults standardUserDefaults] boolForKey:SXNativeUIKey])[self openNativeDrawer]; return;} }
- (void)captureAccountDiagnostics {
    [[DiagnosticsStore shared] addEvent:@"Native drawer account trace" detail:@"captureAccountDiagnostics entered; starting JavaScript" url:self.webView.URL];
    NSString *script=@"(function(){function desc(el){if(!el)return null;var attrs={};Array.from(el.attributes||[]).forEach(function(a){if(a.name==='class'||a.name==='style')return;attrs[a.name]=a.value;});var imgs=Array.from(el.querySelectorAll?el.querySelectorAll('img'):[]).slice(0,8).map(function(i){return {src:i.currentSrc||i.src||'',alt:i.alt||''};});return {tag:el.tagName||'',attrs:attrs,text:(el.innerText||'').trim().slice(0,1200),html:(el.outerHTML||'').slice(0,6000),images:imgs};}var selectors=['[data-testid=DashButton_ProfileIcon_Link]','[data-testid=SideNav_AccountSwitcher_Button]','[data-testid=AccountSwitcher_AddAccount_Button]','[data-testid=AccountSwitcher_Logout_Button]'];var found={};selectors.forEach(function(s){found[s]=desc(document.querySelector(s));});var dialogs=Array.from(document.querySelectorAll('[role=dialog],[role=menu]')).slice(-4).map(desc);return {url:location.href,found:found,dialogs:dialogs};})()";
    [self.webView evaluateJavaScript:script completionHandler:^(id result,NSError *error){
        if(error){ NSString *detail=[NSString stringWithFormat:@"JavaScript failed: %@",error.localizedDescription?:@"unknown error"]; [[DiagnosticsStore shared] addEvent:@"Native drawer account trace" detail:detail url:self.webView.URL]; [[DiagnosticsStore shared] addError:@"Native drawer account DOM capture failed" error:error url:self.webView.URL]; return; }
        NSString *type=result?NSStringFromClass([result class]):@"nil"; [[DiagnosticsStore shared] addEvent:@"Native drawer account trace" detail:[NSString stringWithFormat:@"JavaScript completed; result type=%@",type] url:self.webView.URL];
        NSError *jsonError=nil; NSData *data=[NSJSONSerialization dataWithJSONObject:result?:@{} options:NSJSONWritingPrettyPrinted error:&jsonError]; if(jsonError){ [[DiagnosticsStore shared] addEvent:@"Native drawer account trace" detail:[NSString stringWithFormat:@"JSON serialization failed: %@",jsonError.localizedDescription?:@"unknown error"] url:self.webView.URL]; }
        NSString *detail=data?[[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding]:[result description]; [[DiagnosticsStore shared] addEvent:@"Native drawer account DOM" detail:detail?:@"" url:self.webView.URL];
    }];
}
- (void)openNativeDrawer {
    if(self.nativeDrawer.parentViewController)return;
    [[DiagnosticsStore shared] addEvent:@"Native drawer account trace" detail:@"openNativeDrawer entered" url:self.webView.URL];
    [self captureAccountDiagnostics];
    NSString *script=@"(function(){var q=function(s){return document.querySelector(s)};var profile=q('[data-testid=DashButton_ProfileIcon_Link]');var img=profile&&profile.querySelector('img');var account=q('[data-testid=SideNav_AccountSwitcher_Button]');var texts=account?Array.from(account.querySelectorAll('span')).map(function(x){return (x.innerText||'').trim()}).filter(Boolean):[];var handle=texts.find(function(x){return x.charAt(0)==='@';})||'';var name=texts.find(function(x){return x!==handle;})||'';var following='',followers='';Array.from(document.querySelectorAll('a')).forEach(function(a){var h=a.getAttribute('href')||'';var t=(a.innerText||'').trim();if(h.endsWith('/following')&&!following)following=t.split(/\\s+/)[0]||'';if((h.endsWith('/followers')||h.endsWith('/verified_followers'))&&!followers)followers=t.split(/\\s+/)[0]||'';});return {avatarURL:img?img.currentSrc||img.src||'':'',name:name,handle:handle,following:following,followers:followers};})()";
    __weak typeof(self) weakSelf=self;
    [self.webView evaluateJavaScript:script completionHandler:^(id result,NSError*error){ dispatch_async(dispatch_get_main_queue(),^{ typeof(self) self=weakSelf; if(!self)return; self.nativeDrawer=[NativeDrawerViewController new]; self.nativeDrawer.delegate=self; if([result isKindOfClass:NSDictionary.class])self.nativeDrawer.profileData=result; [self.nativeDrawer presentInParent:self]; }); }];
}
- (void)nativeDrawer:(NativeDrawerViewController*)drawer didSelectPath:(NSString*)path { NSURL*url=[NSURL URLWithString:[@"https://x.com" stringByAppendingString:path]]; [self loadURL:url reason:@"Native drawer"]; }
- (void)nativeDrawerDidSelectScarletSettings:(NativeDrawerViewController*)drawer{[self openSettings];}
- (void)openSettings { UINavigationController*nav=[[UINavigationController alloc] initWithRootViewController:[SettingsViewController new]]; nav.modalPresentationStyle=UIModalPresentationPageSheet; [self presentViewController:nav animated:YES completion:nil]; }
- (void)webView:(WKWebView*)w didStartProvisionalNavigation:(WKNavigation*)n {self.navigationStartTime=CACurrentMediaTime();self.navigationSession++;self.requestPending=NO;}
- (void)webView:(WKWebView*)w didFinishNavigation:(WKNavigation*)n {}
- (void)webView:(WKWebView*)w didFailProvisionalNavigation:(WKNavigation*)n withError:(NSError*)e {[[DiagnosticsStore shared] addError:@"Provisional navigation failed" error:e url:w.URL];}
- (void)webView:(WKWebView*)w didFailNavigation:(WKNavigation*)n withError:(NSError*)e {if([e.domain isEqual:NSURLErrorDomain]&&e.code==NSURLErrorCancelled)return;[[DiagnosticsStore shared] addError:@"Navigation failed" error:e url:w.URL];}
- (void)webViewWebContentProcessDidTerminate:(WKWebView*)w {[[DiagnosticsStore shared] addEvent:@"Web content process terminated" detail:@"" url:w.URL];}
- (void)webView:(WKWebView*)w decidePolicyForNavigationAction:(WKNavigationAction*)a decisionHandler:(void(^)(WKNavigationActionPolicy))d {NSURL*u=a.request.URL;NSString*s=u.scheme.lowercaseString;if([self isWebURL:u]||[s isEqual:@"about"]||[s isEqual:@"blob"]||[s isEqual:@"data"]){d(WKNavigationActionPolicyAllow);return;}d(WKNavigationActionPolicyCancel);}
- (WKWebView*)webView:(WKWebView*)w createWebViewWithConfiguration:(WKWebViewConfiguration*)c forNavigationAction:(WKNavigationAction*)a windowFeatures:(WKWindowFeatures*)f {if(a.targetFrame==nil&&a.request.URL)[w loadRequest:a.request];return nil;}
@end
