#import "MenuScripts.h"

@implementation MenuScripts
+ (NSString *)menuProbeScript {
    return @"var menuProbeDone=false;"
      "function summarizeMenuState(){var layers=document.getElementById('layers');var profile=document.querySelector('[data-testid=DashButton_ProfileIcon_Link]');return {layersChildren:layers?layers.children.length:-1,bodyChildren:document.body?document.body.children.length:-1,profileExpanded:profile?(profile.getAttribute('aria-expanded')||''):'',dialogs:document.querySelectorAll('[role=dialog]').length,menus:document.querySelectorAll('[role=menu]').length};}"
      "var menuLifecycleOpenSeen=false,menuLifecycleCloseSeen=false;"
      "function menuLayerSnapshot(label){var layers=document.getElementById('layers'),kids=layers?Array.from(layers.children):[];send('menu-layer-lifecycle',{label:label,state:summarizeMenuState(),layerChildren:kids.map(function(el,i){return {index:i,tag:el.tagName||'',childCount:el.children?el.children.length:0,hidden:!!el.hidden,ariaHidden:el.getAttribute?el.getAttribute('aria-hidden'):null,display:getComputedStyle(el).display,visibility:getComputedStyle(el).visibility,opacity:getComputedStyle(el).opacity};})});}"
      "var menuLifecycleObserver=null;if((window.__scarletXDiagnostics||{}).menu){menuLifecycleObserver=new MutationObserver(function(){var s=summarizeMenuState();if(!menuLifecycleOpenSeen&&s.profileExpanded==='true'&&s.dialogs>0){menuLifecycleOpenSeen=true;menuLayerSnapshot('opened');}if(menuLifecycleOpenSeen&&!menuLifecycleCloseSeen&&s.profileExpanded!=='true'&&s.dialogs===0){menuLifecycleCloseSeen=true;menuLayerSnapshot('closed-immediate');setTimeout(function(){menuLayerSnapshot('closed-100ms');},100);setTimeout(function(){menuLayerSnapshot('closed-500ms');},500);setTimeout(function(){menuLayerSnapshot('closed-1500ms');},1500);}});menuLifecycleObserver.observe(document.documentElement,{childList:true,subtree:true,attributes:true,attributeFilter:['aria-expanded','aria-hidden','hidden','style']});}"
      "function runMenuInitProbe(){if(menuProbeDone)return;if(!postSent){setTimeout(runMenuInitProbe,250);return;}if(location.pathname!=='/home')return;var btn=document.querySelector('[data-testid=DashButton_ProfileIcon_Link]');if(!btn){send('menu-init-probe-missing',{selector:'DashButton_ProfileIcon_Link'});return;}menuProbeDone=true;var before=summarizeMenuState();var beforeResources=compactSummary();send('menu-init-probe-ready',{state:before,resources:beforeResources});setTimeout(function(){var after=summarizeMenuState();var now=compactSummary();var types={};Object.keys(now.byType).forEach(function(k){var a=now.byType[k],b=beforeResources.byType[k]||{count:0,totalDuration:0,maxDuration:0};var dc=a.count-b.count,dd=a.totalDuration-b.totalDuration;if(dc>0||dd>0)types[k]={count:dc,totalDuration:dd,maxDuration:a.maxDuration};});send('menu-init-probe-idle',{windowMs:1500,state:after,resourceCount:now.count-beforeResources.count,totalResourceDuration:now.totalDuration-beforeResources.totalDuration,byType:types});},1500);}"
      "if((window.__scarletXDiagnostics||{}).menu)setTimeout(runMenuInitProbe,100);";
}

+ (NSString *)menuWarmupScript {
    return @"var hiddenMenuWarmupDone=false,hiddenMenuWarmupActive=false,hiddenMenuWarmupNode=null,hiddenMenuWarmupResources=null,hiddenMenuWarmupResourceTimersStarted=false;"
      "function nativeDrawerEnabled(){return !!window.__scarletXNativeDrawerInstalled;}"
      "function hiddenMenuWarmupResourceDelta(label){if(!hiddenMenuWarmupResources)return;var now=compactSummary(),before=hiddenMenuWarmupResources,types={};Object.keys(now.byType).forEach(function(k){var a=now.byType[k],b=before.byType[k]||{count:0,totalDuration:0,maxDuration:0};var dc=a.count-b.count,dd=a.totalDuration-b.totalDuration;if(dc>0||dd>0)types[k]={count:dc,totalDuration:dd,maxDuration:a.maxDuration};});send('menu-hidden-warmup-resources',{label:label,resourceCount:now.count-before.count,totalResourceDuration:now.totalDuration-before.totalDuration,byType:types,state:summarizeMenuState()});}"
      "function startHiddenMenuWarmupResourceTimers(){if(hiddenMenuWarmupResourceTimersStarted)return;hiddenMenuWarmupResourceTimersStarted=true;hiddenMenuWarmupResourceDelta('dialog-mounted');setTimeout(function(){hiddenMenuWarmupResourceDelta('after-250ms');},250);setTimeout(function(){hiddenMenuWarmupResourceDelta('after-750ms');},750);setTimeout(function(){hiddenMenuWarmupResourceDelta('after-1500ms');},1500);}"
      "function finishHiddenMenuWarmup(reason){if(!hiddenMenuWarmupActive)return;hiddenMenuWarmupActive=false;var btn=document.querySelector('[data-testid=DashButton_ProfileIcon_Link]');if(btn&&btn.getAttribute('aria-expanded')==='true'){try{btn.click();}catch(e){try{document.body.click();}catch(e2){}}}if(hiddenMenuWarmupNode){hiddenMenuWarmupNode.style.removeProperty('opacity');hiddenMenuWarmupNode.style.removeProperty('pointer-events');hiddenMenuWarmupNode.style.removeProperty('transform');hiddenMenuWarmupNode=null;}send('menu-hidden-warmup-finish',{reason:reason,state:summarizeMenuState()});}"
      "var hiddenMenuObserver=new MutationObserver(function(){if(!hiddenMenuWarmupActive)return;var layers=document.getElementById('layers');if(!layers)return;var s=summarizeMenuState();if(s.profileExpanded==='true'&&s.dialogs>0&&layers.children.length>2){var node=layers.lastElementChild;if(node&&!hiddenMenuWarmupNode){hiddenMenuWarmupNode=node;node.style.setProperty('opacity','0','important');node.style.setProperty('pointer-events','none','important');node.style.setProperty('transform','translateX(-200vw)','important');send('menu-hidden-warmup-mounted',{state:s});startHiddenMenuWarmupResourceTimers();setTimeout(function(){finishHiddenMenuWarmup('mounted-700ms');},700);}}});hiddenMenuObserver.observe(document.documentElement,{childList:true,subtree:true,attributes:true,attributeFilter:['aria-expanded']});"
      "function runHiddenMenuWarmup(){if(hiddenMenuWarmupDone||hiddenMenuWarmupActive||!postSent||location.pathname!=='/home'){if(!postSent)setTimeout(runHiddenMenuWarmup,250);return;}var btn=document.querySelector('[data-testid=DashButton_ProfileIcon_Link]');if(!btn)return;hiddenMenuWarmupDone=true;hiddenMenuWarmupActive=true;hiddenMenuWarmupResources=compactSummary();hiddenMenuWarmupResourceTimersStarted=false;send('menu-hidden-warmup-start',{state:summarizeMenuState(),resources:hiddenMenuWarmupResources,nativeDrawer:nativeDrawerEnabled()});try{btn.click();}catch(e){hiddenMenuWarmupActive=false;send('menu-hidden-warmup-error',{message:String(e)});return;}setTimeout(function(){finishHiddenMenuWarmup('timeout-1500ms');},1500);}"
      "setTimeout(runHiddenMenuWarmup,100);";
}
@end
