#import "MenuScripts.h"

@implementation MenuScripts
+ (NSString *)menuProbeScript {
    return @"var menuProbeDone=false;"
      "function summarizeMenuState(){var layers=document.getElementById('layers');var profile=document.querySelector('[data-testid=DashButton_ProfileIcon_Link]');return {layersChildren:layers?layers.children.length:-1,bodyChildren:document.body?document.body.children.length:-1,profileExpanded:profile?(profile.getAttribute('aria-expanded')||''):'',dialogs:document.querySelectorAll('[role=dialog]').length,menus:document.querySelectorAll('[role=menu]').length};}"
      "var menuLifecycleOpenSeen=false,menuLifecycleCloseSeen=false;"
      "function menuLayerSnapshot(label){var layers=document.getElementById('layers'),kids=layers?Array.from(layers.children):[];send('menu-layer-lifecycle',{label:label,state:summarizeMenuState(),layerChildren:kids.map(function(el,i){return {index:i,tag:el.tagName||'',childCount:el.children?el.children.length:0,hidden:!!el.hidden,ariaHidden:el.getAttribute?el.getAttribute('aria-hidden'):null,display:getComputedStyle(el).display,visibility:getComputedStyle(el).visibility,opacity:getComputedStyle(el).opacity};})});}"
      "var menuLifecycleObserver=null;if((window.__scarletXDiagnostics||{}).menu){menuLifecycleObserver=new MutationObserver(function(){var s=summarizeMenuState();if(!menuLifecycleOpenSeen&&s.profileExpanded==='true'&&s.dialogs>0){menuLifecycleOpenSeen=true;menuLayerSnapshot('opened');}if(menuLifecycleOpenSeen&&!menuLifecycleCloseSeen&&s.profileExpanded!=='true'&&s.dialogs===0){menuLifecycleCloseSeen=true;menuLayerSnapshot('closed-immediate');setTimeout(function(){menuLayerSnapshot('closed-100ms');},100);setTimeout(function(){menuLayerSnapshot('closed-500ms');},500);setTimeout(function(){menuLayerSnapshot('closed-1500ms');},1500);}});menuLifecycleObserver.observe(document.documentElement,{childList:true,subtree:true,attributes:true,attributeFilter:['aria-expanded','aria-hidden','hidden','style']});}"
      "function runMenuInitProbe(){if(menuProbeDone)return;if(!postSent){setTimeout(runMenuInitProbe,250);return;}if(location.pathname!=='/home')return;var btn=document.querySelector('[data-testid=DashButton_ProfileIcon_Link]');if(!btn){send('menu-init-probe-missing',{selector:'DashButton_ProfileIcon_Link'});return;}menuProbeDone=true;var before=summarizeMenuState();var beforeResources=compactSummary();send('menu-init-probe-ready',{state:before,resources:beforeResources});setTimeout(function(){var after=summarizeMenuState();var now=compactSummary();var types={};Object.keys(now.byType).forEach(function(k){var a=now.byType[k],b=beforeResources.byType[k]||{count:0,totalDuration:0,maxDuration:0};var dc=a.count-b.count,dd=a.totalDuration-b.totalDuration;if(dc>0||dd>0)types[k]={count:dc,totalDuration:dd,maxDuration:a.maxDuration};});send('menu-init-probe-idle',{windowMs:1500,state:after,resourceCount:now.count-beforeResources.count,totalResourceDuration:now.totalDuration-beforeResources.totalDuration,byType:types});},1500);}"
      "if((window.__scarletXDiagnostics||{}).menu)setTimeout(runMenuInitProbe,100);";
}

+ (NSString *)menuWarmupScript {
    return @"var hiddenMenuWarmupDone=false,hiddenMenuWarmupActive=false,hiddenMenuWarmupNode=null,hiddenMenuWarmupResources=null,hiddenMenuWarmupResourceTimersStarted=false;"
      "function nativeDrawerEnabled(){return !!window.__scarletXNativeDrawerInstalled;}"
      "function hiddenMenuWarmupTrace(stage,payload){try{window.webkit.messageHandlers.scarletx.postMessage({type:'native-drawer-trace',stage:stage,error:JSON.stringify(payload||{})});}catch(e){}}"

      // Existing DOM-only comparison
      "function accountDomProbe(label){try{var labels=[],links=[],pics=[];Array.from(document.querySelectorAll('[aria-label]')).forEach(function(el){var v=el.getAttribute('aria-label')||'';if(v.indexOf('@')>=0||v.indexOf('プロフィール')>=0)labels.push(v);});Array.from(document.querySelectorAll('a[href]')).forEach(function(el){var v=el.getAttribute('href')||'';if(v.length>1&&v.split('/').length===2)links.push(v);});Array.from(document.images||[]).forEach(function(img){var src=img.currentSrc||img.src||'';if(src.indexOf('profile_images')>=0)pics.push(src);});hiddenMenuWarmupTrace('account-dom-'+label,{state:summarizeMenuState(),labels:Array.from(new Set(labels)).slice(0,30),profileLinks:Array.from(new Set(links)).slice(0,30),profileImageCount:(new Set(pics)).size});}catch(e){hiddenMenuWarmupTrace('account-dom-error',{label:label,message:String(e)});}}"

      // Narrow React/Fiber probe: only display/account identity fields.
      "function accountReactProbe(label){try{var root=document.querySelector('[data-testid=DashButton_ProfileIcon_Link]')||document.querySelector('[data-testid=primaryColumn]')||document.body;if(!root){hiddenMenuWarmupTrace('account-react-'+label,{found:false});return;}var seen=new Set(),results=[];function pick(obj,path,depth){if(!obj||typeof obj!=='object'||seen.has(obj)||depth>5||results.length>=40)return;seen.add(obj);var out={};['screen_name','username','name','profile_image_url_https','rest_id'].forEach(function(k){try{var v=obj[k];if(typeof v==='string'&&v.length&&v.length<500)out[k]=v;}catch(e){}});if(Object.keys(out).length)results.push({path:path,values:out});var keys=[];try{keys=Object.keys(obj);}catch(e){return;}keys.slice(0,80).forEach(function(k){if(results.length>=40)return;if(k==='return'||k==='sibling'||k==='child'||k==='stateNode'||k==='alternate')return;var v;try{v=obj[k];}catch(e){return;}if(v&&typeof v==='object')pick(v,path+'.'+k,depth+1);});}var owners=[];for(var el=root,hop=0;el&&hop<5;hop++,el=el.parentElement){var ks=[];try{ks=Object.keys(el);}catch(e){}ks.forEach(function(k){if(k.indexOf('__reactProps$')===0||k.indexOf('__reactFiber$')===0){owners.push({hop:hop,key:k.slice(0,24)});try{pick(el[k],'node['+hop+'].'+k.slice(0,12),0);}catch(e){}}});}hiddenMenuWarmupTrace('account-react-'+label,{state:summarizeMenuState(),ownerCount:owners.length,owners:owners,results:results});}catch(e){hiddenMenuWarmupTrace('account-react-error',{label:label,message:String(e)});}}"

      "function hiddenMenuWarmupResourceDelta(label){if(!hiddenMenuWarmupResources)return;var now=compactSummary(),before=hiddenMenuWarmupResources,types={};Object.keys(now.byType).forEach(function(k){var a=now.byType[k],b=before.byType[k]||{count:0,totalDuration:0,maxDuration:0};var dc=a.count-b.count,dd=a.totalDuration-b.totalDuration;if(dc>0||dd>0)types[k]={count:dc,totalDuration:dd,maxDuration:a.maxDuration};});var payload={label:label,resourceCount:now.count-before.count,totalResourceDuration:now.totalDuration-before.totalDuration,byType:types,state:summarizeMenuState()};hiddenMenuWarmupTrace('warmup-resources-'+label,payload);send('menu-hidden-warmup-resources',payload);}"
      "function startHiddenMenuWarmupResourceTimers(){if(hiddenMenuWarmupResourceTimersStarted)return;hiddenMenuWarmupResourceTimersStarted=true;hiddenMenuWarmupResourceDelta('dialog-mounted');setTimeout(function(){hiddenMenuWarmupResourceDelta('after-250ms');},250);setTimeout(function(){hiddenMenuWarmupResourceDelta('after-750ms');},750);setTimeout(function(){hiddenMenuWarmupResourceDelta('after-1500ms');},1500);}"
      "function finishHiddenMenuWarmup(reason){if(!hiddenMenuWarmupActive)return;hiddenMenuWarmupActive=false;var btn=document.querySelector('[data-testid=DashButton_ProfileIcon_Link]');if(btn&&btn.getAttribute('aria-expanded')==='true'){try{btn.click();}catch(e){try{document.body.click();}catch(e2){}}}if(hiddenMenuWarmupNode){hiddenMenuWarmupNode.style.removeProperty('opacity');hiddenMenuWarmupNode.style.removeProperty('pointer-events');hiddenMenuWarmupNode.style.removeProperty('transform');hiddenMenuWarmupNode=null;}hiddenMenuWarmupTrace('warmup-finish',{reason:reason,state:summarizeMenuState()});send('menu-hidden-warmup-finish',{reason:reason,state:summarizeMenuState()});}"
      "var hiddenMenuObserver=new MutationObserver(function(){if(!hiddenMenuWarmupActive)return;var layers=document.getElementById('layers');if(!layers)return;var s=summarizeMenuState();if(s.profileExpanded==='true'&&s.dialogs>0&&layers.children.length>2){var node=layers.lastElementChild;if(node&&!hiddenMenuWarmupNode){hiddenMenuWarmupNode=node;node.style.setProperty('opacity','0','important');node.style.setProperty('pointer-events','none','important');node.style.setProperty('transform','translateX(-200vw)','important');hiddenMenuWarmupTrace('warmup-mounted',{state:s});accountDomProbe('after-menu-dom');accountReactProbe('after-menu-dom');send('menu-hidden-warmup-mounted',{state:s});startHiddenMenuWarmupResourceTimers();setTimeout(function(){finishHiddenMenuWarmup('mounted-700ms');},700);}}});hiddenMenuObserver.observe(document.documentElement,{childList:true,subtree:true,attributes:true,attributeFilter:['aria-expanded']});"
      "function runHiddenMenuWarmup(){if(hiddenMenuWarmupDone||hiddenMenuWarmupActive||!postSent||location.pathname!=='/home'){if(!postSent)setTimeout(runHiddenMenuWarmup,250);return;}var btn=document.querySelector('[data-testid=DashButton_ProfileIcon_Link]');if(!btn)return;hiddenMenuWarmupDone=true;hiddenMenuWarmupActive=true;hiddenMenuWarmupResources=compactSummary();hiddenMenuWarmupResourceTimersStarted=false;accountDomProbe('before-menu');accountReactProbe('before-menu');var payload={state:summarizeMenuState(),resources:hiddenMenuWarmupResources,nativeDrawer:nativeDrawerEnabled()};hiddenMenuWarmupTrace('warmup-start',payload);send('menu-hidden-warmup-start',payload);try{btn.click();}catch(e){hiddenMenuWarmupActive=false;hiddenMenuWarmupTrace('warmup-error',{message:String(e)});send('menu-hidden-warmup-error',{message:String(e)});return;}setTimeout(function(){finishHiddenMenuWarmup('timeout-1500ms');},1500);}"
      "setTimeout(runHiddenMenuWarmup,100);";
}
@end
